# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170720_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_dot_com]),
        ),
    ]
